#Test Data used within the functionality of logging in and generating a Radiology ETR

#LOGIN DATA
TEST_USERNAME = "username" #Replace with Nadex Username before execution
TEST_PASSWORD = "password" #Replace with Nadex Password before execution

#TEST PATIENT DATA
TEST_NHS_NUMBER = "" #Test Patient: Add in NHS number of test patient
TEST_FEMALE_NHS_NUMBER = "4967843654" #Test Patient: Add NHS number for female patient - used for max data test

#SIGN OFF FORM DATA
SIGNOFF_NAME = "Sharla Passariello"
SIGNOFF_ROLE = "Test Team Principal"
SIGNOFF_GMC = "GMC123456"
SIGNOFF_CONTACT_INFO = "07123465789"

#TEST FORM DATA (STANDARD FORM)
TEST_EXAM = "XR Skull"
TEST_CLINICAL_QUESTION_STANDARD = "This is an electronic request that has been generated automatically using Selenium with Python."
SPECIALITY = "Radiology"
SRC_NAME = "SANDFORD" #Find a test clinician
PATIENT_LOCATION = "GGH Radiography"

#TEST FORM DATA (MINIMUM FORM)
TEST_CLINICAL_QUESTION_MINIMUM = "XR"

#TEST FORM DATA (SPECIAL CHARACTERS FORM)
TEST_CLINICAL_QUESTION_SPECIAL_CHAR =""

#TEST FORM DATA (MAXIMUM FORM)
TEST_CLINICAL_QUESTION_MAXIMUM = ""
REASON_FOR_RBD ="Test Maximum data input for reason required by date 1.Test Maximum data input for reason required by date 2. Test Maximum data input for reason required by date 3.Test Maximum data input for reason required by date 4. Test Maximum data input for reason required by date 5. Test Maximum data input for reason required by date 6.Test Maximum data input for reason required by date 7. Test Maximum data input for reason required by date 8.Test Maximum data input for reason required by date 9.Test Maximum data input for reason required by date 10.Test Maximum data input for reason required by date 11.Test Maximum data input for reason required by date 12.Test Maximum data input for reason required by date 13.Test Maximum data input for reason required by date 14.Test Maximum data input for reason required by date 15.Test Maximum data input for reason required by date 16 Test Maximum data input for reason required by date 17.Test Maximum data input for reason required by date 18.Test Maximum data input for reason required by date 19Test Maximum data input for reason required by date 20."
INFECTION_CONTROL_ISSUES = "Large data input for infection control issues 1. Large data input for infection control issues 2. Large data input for infection control issues 3. Large data input for infection control issues 4. Large data input for infection control issues 5. Large data input for infection control issues 6. Large data input for infection control issues 7. Large data input for infection control issues 8. Large data input for infection control issues 9. Large data input for infection control issues 10. Large data input for infection control issues 11. Large data input for infection control issues 12. Large data input for infection control issues 13. Large data input for infection control issues 14. Large data input for infection control issues 15. Large data input for infection control issues 16. Large data input for infection control issues 17. Large data input for infection control issues 18. Large data input for infection control issues 19. Large data input for infection control issues 20. Large data input for infection control issues 21. Large data input for infection control issues 22. Large data input for infection control issues 23. Large data input for infection control issues 24. Large data input for infection control issues 25. Large data input for infection control issues 26. Large data input for infection control issues 27. Large data input for infection control issues 28. Large data input for infection control issues 29. Large data input for infection control issues 30. Large data input for infection control issues 31. Large data input for infection control issues 32. Large data input for infection control issues 33. Large data input for infection control issues 34. Large data input for infection control issues 35. Large data input for infection control issues 36. Large data input for infection control issues 37. Large data input for infection control issues 38. Large data input for infection control issues 39. Large data input for infection control issues 40. Large data input for infection control issues 41. Large data input for infection control issues 42. Large data input for infection control issues 43. Large data input for infection control issues 44. Large data input for infection control issues 45. Large data input for infection control issues 46. Large data input for infection control issues 47. Large data input for infection control issues 48. Large data input for infection control issues 49. Large data input for infection control issues 50."
OTHER_REL_DETAILS = "Large data set input for non-clinical relevant details 1.Large data set input for non-clinical relevant details 2.Large data set input for non-clinical relevant details 3. Large data set input for non-clinical relevant details 4.Large data set input for non-clinical relevant details 5. Large data set input for non-clinical relevant details 6.Large data set input for non-clinical relevant details 7. Large data set input for non-clinical relevant details 8. Large data set input for non-clinical relevant details 9. Large data set input for non-clinical relevant details 10. Large data set input for non-clinical relevant details 11. Large data set input for non-clinical relevant details 12. Large data set input for non-clinical relevant details 13.Large data set input for non-clinical relevant details 14. Large data set input for non-clinical relevant details 15. Large data set input for non-clinical relevant details 16. Large data set input for non-clinical relevant details 17. Large data set input for non-clinical relevant details 18. Large data set input for non-clinical relevant details 19. Large data set input for non-clinical relevant details 20. Large data set input for non-clinical relevant details 21. Large data set input for non-clinical relevant details 22. Large data set input for non-clinical relevant details 23. Large data set input for non-clinical relevant details 24. Large data set input for non-clinical relevant details 25. Large data set input for non-clinical relevant details 26. Large data set input for non-clinical relevant details 27. Large data set input for non-clinical relevant details 28. Large data set input for non-clinical relevant details 29. Large data set input for non-clinical relevant details 30. Large data set input for non-clinical relevant details 31. Large data set input for non-clinical relevant details 32. Large data set input for non-clinical relevant details 33. Large data set input for non-clinical relevant details 34. Large data set input for non-clinical relevant details 35. Large data set input for non-clinical relevant details 36. Large data set input for non-clinical relevant details 37. Large data set input for non-clinical relevant details 38. Large data set input for non-clinical relevant details 39. Large data set input for non-clinical relevant details 40. Large data set input for non-clinical relevant details 41. Large data set input for non-clinical relevant details 42. Large data set input for non-clinical relevant details 43. Large data set input for non-clinical relevant details 44. Large data set input for non-clinical relevant details 45. Large data set input for non-clinical relevant details 46. Large data set input for non-clinical relevant details 47. Large data set input for non-clinical relevant details 48. Large data set input for non-clinical relevant details 49. Large data set input for non-clinical relevant details 50."
RECENT_REL_RESULTS_NOT_LISTED = "Recent relevant results not listed 1. Recent relevant results not listed 2. Recent relevant results not listed 3. Recent relevant results not listed 4. Recent relevant results not listed 5. Recent relevant results not listed 6. Recent relevant results not listed 7. Recent relevant results not listed 8. Recent relevant results not listed 9. Recent relevant results not listed 10. Recent relevant results not listed 11. Recent relevant results not listed 12. Recent relevant results not listed 13. Recent relevant results not listed 14. Recent relevant results not listed 15. Recent relevant results not listed 16. Recent relevant results not listed 17. Recent relevant results not listed 18. Recent relevant results not listed 19. Recent relevant results not listed 20. Recent relevant results not listed 21. Recent relevant results not listed 22. Recent relevant results not listed 23. Recent relevant results not listed 24. Recent relevant results not listed 25. Recent relevant results not listed 26. Recent relevant results not listed 27. Recent relevant results not listed 28. Recent relevant results not listed 29. Recent relevant results not listed 30. Recent relevant results not listed 31. Recent relevant results not listed 32. Recent relevant results not listed 33. Recent relevant results not listed 34. Recent relevant results not listed 35. Recent relevant results not listed 36. Recent relevant results not listed 37. Recent relevant results not listed 38. Recent relevant results not listed 39. Recent relevant results not listed 40. Recent relevant results not listed 41. Recent relevant results not listed 42. Recent relevant results not listed 43. Recent relevant results not listed 44. Recent relevant results not listed 45. Recent relevant results not listed 46. Recent relevant results not listed 47. Recent relevant results not listed 48. Recent relevant results not listed 49. Recent relevant results not listed 50."
MRI_OTHER_REL_ADD_DETAILS = ""

